### PR TITLE
Update queue.lua to allow protocol field in queues.toml

### PR DESCRIPTION
**Pull request by aryeh**
resolve_config skips all table fields in the queues.toml config subsection, so  adding a protocol field in any of the sections other than [queue.default] gets ignored.

Added an exception in the queue.lua:resolve_config so "protocol" setting fields are not ignored in the the queues.toml  subsections.

### CODE REVIEW

**Comment by wez** [comment]
Thanks for diving in!
Since the logic in these conditionals is growing more complex and a bit repeaty, please refactor this a little:

1. Add a function towards the top of the file:

```lua
local function is_queue_config_option(name, value)
  return name == 'protocol' or type(value) ~= 'table'
end
```

2. Change each of the four `if k == 'protocol' or type(v) ~= 'table' then` lines to:

```lua
   if is_queue_config_option(k, v) then
```

**Comment by aryeh** [comment]
Thanks for the constructive feedback.  I'm still new to participating via github so please pardon me, if I'm not titling work appropriately.

I am going through the kumomta code to really get an full understanding of it, as I try to get it running for my specific needs, and will submit anything I can help with, but aim to tread lightly.  

And I want to fully applaud your work and what you have created.

**Comment by aryeh** [comment]
@wez I've refactored the items as requested.   Do I need to formally submit another pull request?

**Comment by wez** [comment]
Thank you!

**Comment by MHillyer** [comment]
@aryeh are you in our Discord? Please let me know your username so I can assign you the contributor tag!

**Pull request merged**
